name: oc_snapshot
description: A Dart port of CorpNewt's OC Snapshot feature.
version: 0.0.0
repository: https://github.com/Calebh101/oc_snapshot

environment:
  sdk: ^3.10.3

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  plist_parser: ^0.2.6
  propertylistserialization: ^1.4.1
  crypto: ^3.0.7
  xml: ^6.6.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
