name: oc_snapshot
description: Port of CorpNewt's OCSnapshot. Supports both CLI use and Dart use.
version: 0.0.2
repository: https://github.com/Calebh101/oc_snapshot

environment:
  sdk: ^3.10.3

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  plist_parser: ^0.2.6
  crypto: ^3.0.7
  xml: ^6.6.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  oc_snapshot: oc_snapshot
